"""finalize clients table

Revision ID: 3556b5f716a7
Revises: f2aacae15a30
Create Date: 2025-07-03 14:57:36.611224

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3556b5f716a7'
down_revision: Union[str, Sequence[str], None] = 'f2aacae15a30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('contract_type', sa.String(), nullable=False),
    sa.Column('license_type', sa.String(), nullable=False),
    sa.Column('license_start', sa.Date(), nullable=False),
    sa.Column('license_end', sa.Date(), nullable=False),
    sa.Column('manager_name', sa.String(), nullable=False),
    sa.Column('manager_email', sa.String(), nullable=False),
    sa.Column('manager_phone', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('note', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clients_id'), 'clients', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_clients_id'), table_name='clients')
    op.drop_table('clients')
    # ### end Alembic commands ###
