"""add client-like fields to customers table

Revision ID: 4f7db6876245
Revises: 87726361814f
Create Date: 2025-07-03 15:28:49.885093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f7db6876245'
down_revision: Union[str, Sequence[str], None] = '87726361814f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('contract_type', sa.String(), nullable=True))
    op.add_column('customers', sa.Column('license_type', sa.String(), nullable=True))
    op.add_column('customers', sa.Column('license_start', sa.Date(), nullable=True))
    op.add_column('customers', sa.Column('license_end', sa.Date(), nullable=True))
    op.add_column('customers', sa.Column('manager_name', sa.String(), nullable=True))
    op.add_column('customers', sa.Column('manager_email', sa.String(), nullable=True))
    op.add_column('customers', sa.Column('manager_phone', sa.String(), nullable=True))
    op.add_column('customers', sa.Column('location', sa.String(), nullable=True))
    op.add_column('customers', sa.Column('memo', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers', 'memo')
    op.drop_column('customers', 'location')
    op.drop_column('customers', 'manager_phone')
    op.drop_column('customers', 'manager_email')
    op.drop_column('customers', 'manager_name')
    op.drop_column('customers', 'license_end')
    op.drop_column('customers', 'license_start')
    op.drop_column('customers', 'license_type')
    op.drop_column('customers', 'contract_type')
    # ### end Alembic commands ###
