"""rename note to memo in clients table

Revision ID: 87726361814f
Revises: 3556b5f716a7
Create Date: 2025-07-03 15:19:41.304190

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87726361814f'
down_revision: Union[str, Sequence[str], None] = '3556b5f716a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('memo', sa.String(), nullable=True))
    op.drop_column('clients', 'note')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('note', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('clients', 'memo')
    # ### end Alembic commands ###
